# 一个 workflow，名字为Blog Deploy
name: Blog Deploy

# 触发 workflow 的事件
on: push

# 一个workflow由执行的一项或多项job
jobs:
    # 一个job任务，任务名为build
    build:
        # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
        runs-on: ubuntu-latest
        # steps是每个Job的运行步骤，可以包含一个或多个步骤
        steps:
            - name: deploy
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.REMOTE_HOST }}
                port: ${{ secrets.REMOTE_PORT }}
                username: ${{ secrets.REMOTE_USER }}
                key: ${{ secrets.PRIVATE_KEY }}
                # 在需要更新包的时候执行npm install
                script: |
                 cd ./blog-vuepress
                 git pull
                 npm install
                 npm run build