# 一个 workflow，名字为Blog Deploy
name: Blog Deploy

# 触发 workflow 的事件
on: push

# 一个workflow由执行的一项或多项job
jobs:
    # 一个job任务，任务名为build
    build:
        # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
        runs-on: ubuntu-latest
        # steps是每个Job的运行步骤，可以包含一个或多个步骤
        steps:
            # action命令，切换分支获取源码
            - name: Checkout
              # 使用action库  actions/checkout@v2获取源码
              uses: actions/checkout@v2
              with:
                  ref: main
            # action命令，安装Node 14
            - name:
                  install Node.js 14
                  # 使用action库  actions/setup-node安装node
              uses: actions/setup-node@v2
              with:
                  node-version: "14"
                  check-latest: true # 检查14最新的版本
            # action命令，install && test
            - name: npm install # 运行的命令或者 action
              run: npm install
            - name: npm build
              run: npm run build
            - name: multiple command
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.REMOTE_HOST }}
                port: ${{ secrets.REMOTE_PORT }}
                username: ${{ secrets.REMOTE_USER }}
                # password: ${{ secrets.PASSWORD }}
                key: ${{ secrets.PRIVATE_KEY }}
                script: |
                 whoami
                 ls -a
                #  cd ./blog-vuepress
                #  git pull
                #  npm run build